const CONTENT = [
  {
    title: "التقديم على منحة ماجيستير",
    topic: "المنح الدراسية",
    format: "صوتي",
    link: "https://drive.google.com/file/d/1dZ7EGwKbUV4bdytpeYltZPtGHlzMnlBl/view?usp=drive_link",
  },
  {
    title: "التقديم على منحة ماجيستير",
    topic: "المنح الدراسية",
    format: "نص (تفريغ صوتي)",
    link: "https://docs.google.com/document/d/18GpUxSwIqb8YMY9g9xFy-tkoL_rR3Mm_/edit?usp=sharing",
  },
  {
    title: "التقديم على منحة ماجيستير",
    topic: "المنح الدراسية",
    format: "انفوجراف",
    link: "https://drive.google.com/file/d/1qnU8g1GAp3pBtnHsa0niJxFdxNXQrMcm/view?usp=sharing",
  },
  {
    title: "أنواع الدكتوراه",
    topic: "الدكتوراه",
    format: "صوتي",
    link: "https://drive.google.com/file/d/1JTzubLd8NUXnol24Yr9gx3W7lo6aYIJm/view?usp=sharing",
  },
  {
    title: "أنواع الدكتوراه",
    topic: "الدكتوراه",
    format: "انفوجراف",
    link: "https://drive.google.com/file/d/1GnFWtz4pB9DFIAsSqK5k8rKHZvdNWODT/view?usp=sharing",
  },
  {
    title: "أعمل دكتوراه ولا لأ",
    topic: "الدكتوراه",
    format: "صوتي",
    link: "https://drive.google.com/file/d/1lg2Hs_P3vW0Xtxah1V1QFlinFlWnd0WB/view?usp=sharing",
  },
  {
    title: "أنواع الدكتوراه",
    topic: "الدكتوراه",
    format: "نص (تفريغ صوتي)",
    link: "https://docs.google.com/document/d/11PBdMoBdhKT05EPycnbJOQYAsmIpIw-K/edit?usp=sharing",
  },
  {
    title: "قرار الدراسة في الخارج",
    topic: "المنح الدراسية",
    format: "نص (تفريغ صوتي)",
    link: "https://docs.google.com/document/d/1I5ySdWzy25_fl9lUX0JdyFXXMUbNFQTP/edit?usp=sharing",
  },
  {
    title: "قرار الدراسة في الخارج",
    topic: "المنح الدراسية",
    format: "انفوجراف",
    link: "https://drive.google.com/file/d/1tv2rWxPrG0EuKCOiRr4pSGEqjVWTMqoV/view?usp=sharing",
  },
  {
    title: "منحة تشيفننج للماجيستير",
    topic: ["المنح الدراسية", "الماجستير"],
    format: "صوتي",
    link: "https://drive.google.com/file/d/1Rj9fz1o3qcwYD6raAingmYy_Q6n0OjIC/view?usp=sharing",
  },
  {
    title: "منحة تشيفننج للماجيستير",
    topic: ["المنح الدراسية", "الماجستير"],
    format: "نص (تفريغ صوتي)",
    link: "https://docs.google.com/document/d/161tU9G6M8JStx9AnNwTdngB-h_wcqvgp/edit?usp=sharing",
  },
  {
    title: "منحة تشيفننج - دليل مبسط وموضح",
    topic: ["المنح الدراسية", "الماجستير"],
    format: "انفوجراف",
    link: "https://drive.google.com/file/d/1uCdqdgNIvCa_tP5d5CB-cCN38-G4f-a5/view?usp=sharing",
  },
  {
    title: "الدكتوراه عن طريق النشر الأكاديمي",
    topic: ["الدكتوراه", "النشر الأكاديمي"],
    format: "صوتي",
    link: "https://drive.google.com/file/d/19VGagQkvsedVwEMrZ5ZhL2wS7YN7pVs8/view?usp=sharing",
  },
  {
    title: "الدكتوراه عن طريق النشر الأكاديمي",
    topic: ["الدكتوراه", "النشر الأكاديمي"],
    format: "نص (تفريغ صوتي)",
    link: "https://docs.google.com/document/d/13KdtiW4BGzXzI6NmWxn7zyg7WXI7br7E/edit?usp=sharing",
  },
  {
    title: "الدكتوراه عن طريق النشر الأكاديمي",
    topic: ["الدكتوراه", "النشر الأكاديمي"],
    format: "انفوجراف",
    link: "https://drive.google.com/file/d/1xfBH_NtIT9A-SmWj2EhlTJSDn8C98a2K/view?usp=sharing",
  },
  {
    title: "أبحاث ما بعد الدكتوراه",
    topic: "ما بعد الدكتوراه",
    format: "نص (تفريغ صوتي)",
    link: "https://docs.google.com/document/d/1F6Wun9dNEav-65mf8IlX-f2YbrH09aMF/edit?usp=sharing",
  },
  {
    title: "أبحاث ما بعد الدكتوراه",
    topic: "ما بعد الدكتوراه",
    format: "صوتي",
    link: "https://drive.google.com/file/d/1Br-IauOcUezSsmk6sW9VQHOHxNqpWUcM/view?usp=sharing",
  },
  {
    title: "التقديم لزمالات ما بعد الدكتوراه",
    topic: "ما بعد الدكتوراه",
    format: "انفوجراف",
    link: "https://drive.google.com/file/d/10J2ZbU9kZpTtkFXZ8G8TKp8S-BC00Vo-/view?usp=sharing",
  },
  {
    title: "الفرق بين الدورية العربية والاجنبية",
    topic: "النشر الأكاديمي",
    format: "صوتي",
    link: "https://drive.google.com/file/d/19VGagQkvsedVwEMrZ5ZhL2wS7YN7pVs8/view?usp=sharing",
  },
  {
    title: "الفرق بين الدورية العربية والاجنبية",
    topic: "النشر الأكاديمي",
    format: "نص (تفريغ صوتي)",
    link: "https://docs.google.com/document/d/13KdtiW4BGzXzI6NmWxn7zyg7WXI7br7E/edit?usp=sharing",
  },
  {
    title: "الفرق بين الدورية العربية والاجنبية",
    topic: "النشر الأكاديمي",
    format: "انفوجراف",
    link: "https://gamma.app/docs/-inmn0djefrvnuho",
  },
];
